name: sensarp-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6*
  - netCDF4>=1.5
  - pyyaml>=3.12
  - pyproj>=2.2
  - xarray
  # Docs
  - sphinxcontrib-bibtex>=0.4
  # For testing
  - pytest>=4.6
