# conda env create|update -f environment.yml
name: sensarp-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6*
  - netCDF4>=1.5
  - pyyaml>=3.12
  - pyproj>=2.2
  - xarray
  - sphinxcontrib-bibtex>=0.4 # docs
  - pytest>=4.6 # testing
  - gdal>=3.0.4
  - jupyter
  - pip
  - pip:
    - sentinelsat==0.13
