
# Input folder with SAR data (zip format)
input_folder: '/media/tweiss/Daten/test_mysentinelapi'

# Folder to store the pre-processed data
output_folder: '/media/tweiss/Daten/test_mysentinelapi'

# Location of SNAP's graph-processing-tool
gpt: /home/tweiss/snap/bin/gpt

# Location of xml files for processing (not needed if default version is used)
#xml_graph_path: /media/tweiss/Work/GIT/GitHub/multiply-org/sar-pre-processing/sar_pre_processing/user_defined_graphs

# file names of xml graphs (not needed if default version is used)
#pre_process_step1: test_pre_process_step1.xml
#pre_process_step1_border: test_pre_process_step1_border.xml
#pre_process_step2: test_pre_process_step2.xml
#pre_process_step3: test_pre_process_step3.xml
region:
  subset: 'no'
  ul:
    lat: 48.40
    lon: 11.60
  lr:
    lat: 48.10
    lon: 11.90

speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '5'

single_file: 'no'

# not needed if default version is used
#normalisation_angle: 35

