---
gpt: /home/wodan/snap/bin/gpt
input_folder: /path/to/data/
output_folder: /path/to/data/
region:
  lr:
    lat: 48.2
    lon: 11.9
  subset: 'yes'
  ul:
    lat: 48.4
    lon: 11.6
single_file: 'no'
speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '5'
use_user_defined_graphs: 'yes'
year: '2021'
