---
gpt: /home/tweiss/snap/bin/gpt
input_folder: /media/tweiss/Work/GIT/GitHub/multiply-org/sar-pre-processing/docs/notebooks/test_files
output_folder: /media/tweiss/Work/GIT/GitHub/multiply-org/sar-pre-processing/docs/notebooks/test_files
speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '5'

