---
gpt: /home/tweiss/snap/bin/gpt
input_folder: /media/nas_data/Thomas/S1/data/Wallerfing_MNI
output_folder: /media/nas_data/Thomas/S1/processed/MNI_2017_new_final
region:
  lr:
    lat: 48.1
    lon: 11.9
  ul:
    lat: 48.4
    lon: 11.6
speckle_filter:
  multi_temporal:
    apply: 'yes'
    files: '5'
  single_filter:
    apply: 'yes'
subset: 'yes'
year: '2017'
